#!/bin/bash

cd $BUILD_DIR
rm -rf bash-$BASH_VER
tar -xf $SOURCE_DIR/bash-$BASH_VER.tar.gz


cd $BUILD_DIR
rm -rf bash-build
mkdir -p bash-build
cd bash-build

../bash-$BASH_VER/configure \
  --host=$TARGET --prefix= \
  --with-curses --without-bash-malloc
  
make DESTDIR=$HURD_DIR install

cd $HURD_DIR/bin
ln -s bash sh

cd $ROOT
