#!/bin/bash

cd $SOURCE_DIR
tar -xf mig-$MIG_VER.tar.gz
cd mig-$MIG_VER
autoreconf -vif

rm -rf $BUILD_DIR/mig
mkdir  $BUILD_DIR/mig
cd $BUILD_DIR/mig

$SOURCE_DIR/mig-$MIG_VER/configure \
  --target=$TARGET \
  --prefix=$INSTALL_DIR

make all install

cd $ROOT
