#!/bin/bash

cd $SOURCE_DIR
rm -rf binutils-$BINUTILS_VER
tar -xf binutils-$BINUTILS_VER.tar.bz2

cd $BUILD_DIR

rm -rf binutils
mkdir binutils
cd binutils

$SOURCE_DIR/binutils-$BINUTILS_VER/configure \
  --target=$TARGET \
  --prefix=$INSTALL_DIR \
  --with-sysroot=$HURD_DIR \
  --disable-nls \
  --disable-werror

make MAKEINFO=true all install

cd $ROOT
