#!/bin/bash

cd $SOURCE_DIR
rm -rf binutils-$BINUTILS_VER
tar -xf binutils-$BINUTILS_VER.tar.*

rm -rf $BUILD_DIR/binutils
mkdir  $BUILD_DIR/binutils
cd $BUILD_DIR/binutils

unset MAKEFLAGS

$SOURCE_DIR/binutils-$BINUTILS_VER/configure \
  --target=$TARGET \
  --prefix=$INSTALL_DIR \
  --with-sysroot=$HURD_DIR \
  --disable-nls \
  --disable-werror 

make MAKEINFO=true all install

export MAKEFLAGS="-j 48"
cd $ROOT
