#! /bin/sh

cd $SOURCE_DIR
# rm -rf gcc-$GCC_VER

tar -xf gcc-$GCC_VER.tar.*

tar -C gcc-$GCC_VER -xf mpfr-$MPFR_VER.tar.*
tar -C gcc-$GCC_VER -xf gmp-$GMP_VER.tar.*
tar -C gcc-$GCC_VER -xf mpc-$MPC_VER.tar.*

cd gcc-$GCC_VER
mv mpfr-$MPFR_VER mpfr
mv gmp-$GMP_VER gmp
mv mpc-$MPC_VER mpc

rm -rf   $BUILD_DIR/gcc
mkdir -p $BUILD_DIR/gcc
cd $BUILD_DIR/gcc


$SOURCE_DIR/gcc-$GCC_VER/configure \
  --target=$TARGET \
  --prefix=$INSTALL_DIR \
  --with-sysroot=$HURD_DIR \
  --with-newlib \
  --enable-languages=c,c++ \
  --with-arch=i686 \
  --disable-nls \
  --disable-shared \
  --disable-threads \
  --disable-decimal-float \
  --disable-libatomic \
  --disable-libgomp \
  --disable-libitm \
  --disable-libmudflap \
  --disable-libquadmath \
  --disable-libsanitizer \
  --disable-libssp \
  --disable-libstdc++-v3 \
  --without-headers \
  --with-mpfr=$SOURCE_DIR/gcc-$GCC_VER/mpfr \
  --with-gmp=$SOURCE_DIR/gcc-$GCC_VER/gmp \
  --with-mpc=$SOURCE_DIR/gcc-$GCC_VER/mpc

make all-gcc all-target-libgcc
make install-gcc install-target-libgcc
  
# glibc tries to link to this
echo '/* Empty.  */' > $HURD_DIR/lib/libgcc_eh.a

# prepare for pass 2
rm -f config.status config.cache */config.cache */*/config.cache

cd $ROOT
