#! /bin/sh

cd $BUILD_DIR/gcc

$SOURCE_DIR/gcc-$GCC_VER/configure \
  --target=$TARGET \
  --prefix=$INSTALL_DIR \
  --with-sysroot=$HURD_DIR \
  --with-newlib \
  --enable-languages=c,c++ \
  --with-arch=i686 \
  --disable-nls \
  --disable-shared \
  --disable-threads \
  --disable-decimal-float \
  --disable-libatomic \
  --disable-libgomp \
  --disable-libitm \
  --disable-libmudflap \
  --disable-libquadmath \
  --disable-libsanitizer \
  --disable-libssp \
  --disable-libstdc++-v3 \
  --without-headers \
  --with-mpfr=$SOURCE_DIR/gcc-$GCC_VER/mpfr \
  --with-gmp=$SOURCE_DIR/gcc-$GCC_VER/gmp \
  --with-mpc=$SOURCE_DIR/gcc-$GCC_VER/mpc

make all

# clean up files installed in pass 1
rm -f $HURD_DIR/lib/libgcc_eh.a $INSTALL_DIR/lib/gcc/$TARGET/$GCC_VER/{libgcc.a,libgcov.a}

make install

cd $ROOT
