#!/bin/bash

cd $SOURCE_DIR/mig
git pull origin
autoreconf -vif

rm -rf $BUILD_DIR/mig
cp -a $SOURCE_DIR/mig $BUILD_DIR
cd $BUILD_DIR/mig


$SOURCE_DIR/mig/configure \
  --target=$TARGET \
  --prefix=$INSTALL_DIR

make all install

cd $ROOT
