#!/bin/bash

export CC=$TARGET-gcc
export CXX=$TARGET-g++
export AR=$TARGET-ar
export AS=$TARGET-as
export RANLIB=$TARGET-ranlib
export LD=$TARGET-ld
export STRIP=$TARGET-strip

export CFLAGS="$CFLAGS -march=${TARGET%%-*}"
