#!/bin/bash

cd $BUILD_DIR
rm -rf findutils-$FINDUTILS_VER
tar -xf $SOURCE_DIR/findutils-$FINDUTILS_VER.tar.gz

rm -rf findutils-build
mkdir -p findutils-build
cd findutils-build

../findutils-$FINDUTILS_VER/configure \
  --host=$TARGET \
  --prefix=
make DESTDIR=$HURD_DIR install

cd $ROOT
