#!/bin/bash

source ./scripts/pkgver

cd $SOURCE_DIR

# binutils
wget -nc http://ftp.gnu.org/gnu/binutils/binutils-$BINUTILS_VER.tar.gz

# gcc
wget -nc http://ftp.gnu.org/gnu/gcc/gcc-$GCC_VER/gcc-$GCC_VER.tar.bz2

# glibc
if [ ! $GLIBC_GIT -eq 1 ]; then
    wget -nc http://git.savannah.gnu.org/cgit/hurd/glibc.git/snapshot/glibc-$GLIBC_VER.tar.gz
fi
# gmp
wget -nc ftp://ftp.gnu.org/gnu/gmp/gmp-$GMP_VER.tar.bz2
  
# hurd
wget -nc http://git.savannah.gnu.org/cgit/hurd/hurd.git/snapshot/hurd-$HURD_VER.tar.gz

# mach
wget -nc http://git.savannah.gnu.org/cgit/hurd/gnumach.git/snapshot/gnumach-$MACH_VER.tar.gz

# mpc
wget -nc http://ftp.gnu.org/gnu/mpc/mpc-$MPC_VER.tar.gz

# mig
wget -nc http://git.savannah.gnu.org/cgit/hurd/mig.git/snapshot/mig-$MIG_VER.tar.gz

# mpfr
wget -nc http://mpfr.loria.fr/mpfr-current/mpfr-$MPFR_VER.tar.bz2

if [ $GLIBC_GIT -eq 1 ]; then
    # Use http method (more generic)
    GIT_ROOT=http://git.savannah.gnu.org/r/hurd
    for pkg in glibc; do
	if [ -d $SOURCE_DIR/$pkg ]; then
	    cd $SOURCE_DIR/$pkg && git pull origin
	else
	    cd $SOURCE_DIR
	    git clone $GIT_ROOT/$pkg
	    cd glibc
	    git checkout tschwinge/Roger_Whittaker

            # Fix for make version being too new
	    sed -i "s/^  ac_prog_version=\`\$MAKE.*$/  ac_prog_version=3.9/" configure

            # Fix the reference to pthread.h
	    sed -i 's:#include_next.*:#include <pthread/pthread.h>:' include/pthread.h

            # Fix the missing hurd_atfork_prepare_hook error
	    git apply $SOURCE_DIR/patches/glibc/hurd_atfork_hooks.patch
	fi
    done
fi

if [ ! -d $SOURCE_DIR/hurd-$HURD_VER ]; then
  cd $SOURCE_DIR
  tar -xf hurd-$HURD_VER.tar.gz
  cd $SOURCE_DIR/hurd-$HURD_VER
  if [ -d libpthread ]; then
      cd libpthread && git pull
  else
      git clone $GIT_ROOT/libpthread.git
      cd libpthread
      git checkout tschwinge/Peter_Herbolzheimer
  fi
fi

cd $ROOT