#! /bin/bash

cd $SOURCE_DIR/glibc
git pull origin
# fix for binutils>=2.20
sed -i 's#2.1\[3-9\]\*#2.2\[0-9\]\*#' configure
sed -i 's/ot \$/ot:\n\ttouch $@\n$/' manual/Makefile

rm -rf $BUILD_DIR/glibc
mkdir -p $BUILD_DIR/glibc
cd $BUILD_DIR/glibc

CFLAGS="$CFLAGS -O2 -march=${TARGET%%-*}" \
$SOURCE_DIR/glibc/configure \
  --build=$HOST \
  --host=$TARGET \
  --prefix= \
  --with-headers=$SYS_ROOT/include \
  --without-cvs \
  --disable-profile
  
make all
make install_root=$SYS_ROOT install
ln -sf ld.so.1 $SYS_ROOT/lib/ld.so
  
# prepare for pass 2
rm -f $BUILD_DIR/glibc/config.status

cd $ROOT
