#! /bin/bash

# Note: using source and build directories from pass1

cd $BUILD_DIR/glibc-build

CFLAGS="$CFLAGS -O2 -march=${TARGET%%-*}" \
../glibc-$GLIBC_VER/configure \
  --without-cvs \
  --build=$HOST \
  --host=$TARGET \
  --prefix= \
  --with-headers=$HURD_DIR/include \
  --disable-profile

make all
make install_root=$HURD_DIR install

cd $ROOT
