#! /bin/bash

cd $BUILD_DIR/glibc

CFLAGS="$CFLAGS -O2 -march=${TARGET%%-*}" \
$SOURCE_DIR/glibc/configure \
  --build=$HOST \
  --host=$TARGET \
  --prefix= \
  --with-headers=$HURD_DIR/include \
  --without-cvs \
  --disable-profile

make all
make install_root=$HURD_DIR install

cd $ROOT
