#!/bin/bash

cd $SOURCE_DIR/gnumach
git pull origin
autoreconf -vif

rm -rf $BUILD_DIR/gnumach
cp -a $SOURCE_DIR/gnumach $BUILD_DIR
cd $BUILD_DIR/gnumach

CC=gcc \
$SOURCE_DIR/gnumach/configure \
  --host=$TARGET \
  --prefix=
  
make DESTDIR=$SYS_ROOT install-data

cd $ROOT
