#!/bin/bash

cd $SOURCE_DIR/gnumach-$MACH_VER
autoreconf -vif

cd $BUILD_DIR
rm -rf $BUILD_DIR/gnumach
mkdir  $BUILD_DIR/gnumach
cd $BUILD_DIR/gnumach

$SOURCE_DIR/gnumach-$MACH_VER/configure \
  --enable-kdb \
  --host=$TARGET \
  --prefix=
  
make
make DESTDIR=$HURD_DIR install

cd $ROOT
