#!/bin/bash

cd $SOURCE_DIR
tar -xf gnumach-$MACH_VER.tar.gz
cd gnumach-$MACH_VER
autoreconf -vif

rm -rf $BUILD_DIR/gnumach
mkdir $BUILD_DIR/gnumach
cd $BUILD_DIR/gnumach

CC=gcc \
$SOURCE_DIR/gnumach-$MACH_VER/configure \
  --host=$TARGET \
  --prefix= \
  
make DESTDIR=$HURD_DIR install-data

cd $ROOT
