#!/bin/bash

cd $BUILD_DIR
rm -rf grep-$GREP_VER
tar -xf $SOURCE_DIR/grep-$GREP_VER.tar.bz2

rm -rf grep-build
mkdir -p grep-build
cd grep-build

../grep-$GREP_VER/configure \
    --prefix= \
    --host=$TARGET \
    --disable-perl-regexp \
    --without-included-regex
make DESTDIR=$HURD_DIR install

cd $ROOT



