#!/bin/bash

cd $BUILD_DIR
rm -rf grub-$GRUB_VER
tar -xf $SOURCE_DIR/grub-$GRUB_VER.tar.gz

rm -rf grub-build
mkdir -p grub-build
cd grub-build

../grub-$GRUB_VER/autogen.sh
../grub-$GRUB_VER/configure \
  --host=$TARGET \
  --prefix=
make DESTDIR=$HURD_DIR install

cd $ROOT
