#!/bin/bash

cd $BUILD_DIR
rm -rf gzip-$GZIP_VER
tar -xf $SOURCE_DIR/gzip-$GZIP_VER.tar.gz
cd gzip-$GZIP_VER

cd $BUILD_DIR
rm -rf gzip-build
mkdir -p gzip-build
cd gzip-build

../gzip-$GZIP_VER/configure \
    --host=$TARGET \
    --prefix=
make DESTDIR=$HURD_DIR install

cd $ROOT