#!/bin/bash

cd $SOURCE_DIR/hurd-$HURD_VER
autoreconf -vif

rm -rf $BUILD_DIR/hurd
mkdir -p $BUILD_DIR/hurd
cd $BUILD_DIR/hurd

unset MAKEFLAGS
CC=gcc \
$SOURCE_DIR/hurd-$HURD_VER/configure \
  --host=$TARGET \
  --prefix= \
  --disable-profile \
  --without-parted
  
make prefix=$HURD_DIR no_deps=t install-headers
make -C libpthread prefix=$HURD_DIR no_deps=t install-headers


# prepare for libpthread build
rm config.status
export MAKEFLAGS="-j 48"

cd $ROOT
