#!/bin/bash

cd $BUILD_DIR
rm -rf libfetch-$LIBFETCH_VER
tar -xf $SOURCE_DIR/libfetch-$LIBFETCH_VER.tar.gz

cd libfetch-$LIBFETCH_VER

cp $SOURCE_DIR/patches/libfetch/Makefile .

patch -p2 < $SOURCE_DIR/patches/libfetch/libfetch_hurd.patch

make
make DESTDIR=$HURD_DIR install

cd $ROOT
