#!/bin/bash

# NOTE: using source prepare for hurd-headers

cd $BUILD_DIR

CFLAGS="$CFLAGS -march=${TARGET%%-*}" \
$SOURCE_DIR/hurd/configure \
  --host=$TARGET \
  --prefix= \
  --disable-profile

make libpthread
make prefix=$SYS_ROOT libihash-install libpthread-install

cd $ROOT
