#!/bin/bash

# NOTE: using source prepare for hurd-headers

rm -rf $BUILD_DIR/libpthread
mkdir -p $BUILD_DIR/libpthread
cd $BUILD_DIR/libpthread

CFLAGS="$CFLAGS -march=${TARGET%%-*}" \
$SOURCE_DIR/hurd-$HURD_VER/configure \
  --host=$TARGET \
  --prefix= \
  --disable-profile \
  --without-parted

make libpthread
make prefix=$HURD_DIR libihash-install libpthread-install

cd $ROOT
