#! /bin/bash


source ./scripts/prepare
source ./scripts/pkgver
mkdir -p $ROOT/logs

# Part. I:
# ========

if [ "$1" == "all" ]; then
    for f in get-sources cross-binutils cross-gcc-pass1 gnumach-headers cross-mig hurd-headers glibc-pass1 libpthread cross-gcc-pass2 glibc-pass2; do
	source ./scripts/$f 2>&1 | tee $ROOT/logs/$f-$(date +%y%m%d-%H%M%S).log
    done
else
    for f in $@; do
	source ./scripts/$f 2>&1 | tee $ROOT/logs/$f-$(date +%y%m%d-%H%M%S).log
    done
fi
