#!/bin/bash

cd $SOURCE_DIR
if [ ! -f pacman-$PACMAN_VER.tar.gz ]; then
  wget ftp://ftp.archlinux.org/other/pacman/pacman-$PACMAN_VER.tar.gz
fi

cd $BUILD_DIR
rm -rf pacman-$PACMAN_VER
tar -xf $SOURCE_DIR/pacman-$PACMAN_VER.tar.gz

cd pacman-$PACMAN_VER

#sed -i 's@\(LIBS="-lfetch\).*@\1 -lssl -lcrypto -ldl $LIBS"@g' ../pacman-$PACMAN_VER/configure
patch -p2 < $SOURCE_DIR/patches/pacman/pacman_hurd.patch

autoconf 
./configure \
    --host=$TARGET \
    --prefix=

LIBRARY_PATH=$HURD_DIR/local/lib CPATH=$HURD_DIR/local/include make DESTDIR=$HURD_DIR install

cd $ROOT



