#!/bin/bash

cd $BUILD_DIR
rm -rf patch-$PATCH_VER
tar -xf $SOURCE_DIR/patch-$PATCH_VER.tar.bz2

rm -rf patch-build
mkdir -p patch-build
cd patch-build

../patch-$PATCH_VER/configure \
    --host=$TARGET \
    --prefix= 
make DESTDIR=$HURD_DIR install

cd $ROOT
