#! /bin/bash



#cd $SOURCE_DIR
#if [ ! -f ppl-$PPL_VER.tar.bz2 ]; then
#  wget ftp://ftp.cs.unipr.it/pub/ppl/releases/$PPL_VER/ppl-$PPL_VER.tar.bz2
#fi

cd $BUILD_DIR
rm -rf ppl-$PPL_VER
tar -xf $SOURCE_DIR/ppl-$PPL_VER.tar.bz2

rm -rf ppl-build
mkdir -p ppl-build
cd ppl-build

../ppl-$PPL_VER/configure \
    --host=$TARGET --build=$HOST\
    --prefix=

make DESTDIR=$HURD_DIR install


rm $HURD_DIR/lib/libppl.la $HURD_DIR/lib/libppl_c.la

cd $ROOT


