#!/bin/bash

ROOT=~/archhurd/melpo/hurd
HOST=x86_64-unknown-gnu
TARGET=i586-pc-gnu

# clear system variables
export LC_ALL=C
unset CC CXX AR AS RANLIB LD STRIP
unset ASFLAGS CFLAGS CPPFLAGS CXXFLAGS LDFLAGS

export CFLAGS="-O2 -pipe"  # -march=${TARGET%%-*} will be added for cross compiled code

# prepare directories
export SOURCE_DIR=$ROOT/source
export BUILD_DIR=$ROOT/build
export CROSS_DIR=$ROOT/cross
export HURD_DIR=$ROOT/hurd
mkdir -p $SOURCE_DIR $BUILD_DIR $CROSS_DIR $HURD_DIR

mkdir -p $CROSS_DIR/{bin,$TARGET}
export PATH=$CROSS_DIR/bin:$PATH

# prepare hurd layout
cd $HURD_DIR
ln -sf . usr &>/dev/null
mkdir -p $HURD_DIR/{include,lib}
ln -sfn $HURD_DIR/{include,lib} $CROSS_DIR/$TARGET/

cd $ROOT
