#!/bin/bash

ROOT=~/hurd_toolchain

export SOURCE_DIR=$ROOT/source
export BUILD_DIR=$ROOT/build
export INSTALL_DIR=$ROOT/install
export HURD_DIR=$ROOT/hurd

HOST=i686-pc-linux-gnu
TARGET=i686-pc-gnu

# prepare directories
mkdir -p $SOURCE_DIR $BUILD_DIR $INSTALL_DIR $INSTALL_DIR/{bin,$TARGET} $HURD_DIR

export PATH=$INSTALL_DIR/bin:$PATH

cd $HURD_DIR
ln -sf . usr &>/dev/null
mkdir -p include lib
ln -sfn $HURD_DIR/{include,lib} $INSTALL_DIR/$TARGET/



# clear system variables
export LC_ALL=C
export CFLAGS="-O2 -pipe"
unset CC CXX AR AS RANLIB LD STRIP ASFLAGS CPPFLAGS CXXFLAGS LXFLAGS MAKEFLAGS
export MAKEFLAGS="-j 48"

# Use git repo for glibc
export GLIBC_GIT=1

cd $ROOT
